# Use uma imagem base do Node.js
FROM node:14

# Defina o diretório de trabalho
WORKDIR /app

# Copie o package.json e package-lock.json
COPY frontend/package*.json ./

# Instale as dependências
RUN npm install

# Copie o restante do código
COPY frontend/ ./

# Execute a build do Vue.js
RUN npm run build

# Exponha a porta 80
EXPOSE 80

# Comando para iniciar o servidor
CMD ["npm", "run", "serve"]
