# Use uma imagem base do Nginx
FROM nginx:alpine

# Copie o arquivo de configuração do Nginx
COPY nginx/nginx.conf /etc/nginx/nginx.conf
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
COPY nginx/fastcgi-php.conf /etc/nginx/snippets/fastcgi-php.conf

# Exponha a porta 80
EXPOSE 80
